export const TYPES = {
  DEPOSIT: 'DEPOSIT',
  PAYMENT: 'PAYMENT',
  TRANSFER: 'TRANSFER',
};

export const TRANSFER_TYPE = {
  CARD_TO_CARD: 'CARD-TO-CARD',
  ACCOUNT_CARD: 'ACCOUNT-CARD',
  ACCOUNT_SERVICE: 'ACCOUNT=SERVICE',
};

export const SERVICE_TYPES = {
  DEPOSIT: 'DEPOSIT',
  LOAN: 'LOAN',
};

export const ACTION_TYPE = {
  DELETE: 'DELETE',
  ADD: 'ADD',
};
